### ISSUE TITLE
[CENTOS 8] gstatus not working with gluster v8

### ISSUE THREAD

**Issue by hunter86bg** [gluster/gstatus#30]
I have some rpms build from 8.0 source and it seems that gstatus fails to work:

RPMS:
```
[root@glustera gstatus]# rpm -qa | grep -E "gluster|python" | sort
glusterfs-8.0-0.0.el8.x86_64
glusterfs-cli-8.0-0.0.el8.x86_64
glusterfs-client-xlators-8.0-0.0.el8.x86_64
glusterfs-fuse-8.0-0.0.el8.x86_64
glusterfs-gnfs-8.0-0.0.el8.x86_64
glusterfs-server-8.0-0.0.el8.x86_64
libglusterd0-8.0-0.0.el8.x86_64
libglusterfs0-8.0-0.0.el8.x86_64
platform-python-3.6.8-23.el8.x86_64
platform-python-pip-9.0.3-16.el8.noarch
platform-python-setuptools-39.2.0-5.el8.noarch
policycoreutils-python-utils-2.9-9.el8.noarch
python2-2.7.17-1.module_el8.2.0+381+9a5b3c3b.x86_64
python2-libs-2.7.17-1.module_el8.2.0+381+9a5b3c3b.x86_64
python2-pip-9.0.3-16.module_el8.2.0+381+9a5b3c3b.noarch
python2-pip-wheel-9.0.3-16.module_el8.2.0+381+9a5b3c3b.noarch
python2-setuptools-39.0.1-11.module_el8.2.0+381+9a5b3c3b.noarch
python2-setuptools-wheel-39.0.1-11.module_el8.2.0+381+9a5b3c3b.noarch
python36-3.6.8-2.module_el8.1.0+245+c39af44f.x86_64
python3-audit-3.0-0.17.20191104git1c2f876.el8.x86_64
python3-cairo-1.16.3-6.el8.x86_64
python3-configobj-5.0.6-11.el8.noarch
python3-dateutil-2.6.1-6.el8.noarch
python3-dbus-1.2.4-15.el8.x86_64
python3-decorator-4.2.1-2.el8.noarch
python3-dmidecode-3.12.2-15.el8.x86_64
python3-dnf-4.2.17-6.el8.noarch
python3-dnf-plugins-core-4.0.12-3.el8.noarch
python3-firewall-0.8.0-4.el8.noarch
python3-gobject-3.28.3-1.el8.x86_64
python3-gobject-base-3.28.3-1.el8.x86_64
python3-gpg-1.10.0-6.el8.0.1.x86_64
python3-hawkey-0.39.1-5.el8.x86_64
python3-libcomps-0.1.11-4.el8.x86_64
python3-libdnf-0.39.1-5.el8.x86_64
python3-libs-3.6.8-23.el8.x86_64
python3-libselinux-2.9-3.el8.x86_64
python3-libsemanage-2.9-2.el8.x86_64
python3-libxml2-2.9.7-7.el8.x86_64
python3-linux-procfs-0.6-7.el8.noarch
python3-nftables-0.9.3-12.el8.x86_64
python3-perf-4.18.0-193.14.2.el8_2.x86_64
python3-pip-9.0.3-16.el8.noarch
python3-pip-wheel-9.0.3-16.el8.noarch
python3-policycoreutils-2.9-9.el8.noarch
python3-pyudev-0.21.0-7.el8.noarch
python3-pyxattr-0.5.3-18.el8.x86_64
python3-rpm-4.14.2-37.el8.x86_64
python3-schedutils-0.6-6.el8.x86_64
python3-setools-4.2.2-2.el8.x86_64
python3-setuptools-39.2.0-5.el8.noarch
python3-setuptools-wheel-39.2.0-5.el8.noarch
python3-six-1.11.0-8.el8.noarch
python3-slip-0.6.4-11.el8.noarch
python3-slip-dbus-0.6.4-11.el8.noarch
python3-syspurpose-1.26.17-1.el8_2.x86_64
python3-systemd-234-8.el8.x86_64
samba-vfs-glusterfs-4.11.11-1.el8.x86_64
```

Python2 fails with:
```
[root@glustera gstatus]# /usr/bin/python2.7 ./gstatus.py 
 
Traceback (most recent call last):  
  File "./gstatus.py", line 244, in <module>
    main()
  File "./gstatus.py", line 132, in main
    cluster.initialise()
  File "/root/gstatus/gstatus/libgluster/cluster.py", line 97, in initialise
    self.define_nodes()
  File "/root/gstatus/gstatus/libgluster/cluster.py", line 170, in define_nodes
    local_ip_list = get_ipv4_addr()  # Grab all IP's
  File "/root/gstatus/gstatus/libutils/network.py", line 130, in get_ipv4_addr
    namestr = names.tobytes()
AttributeError: 'array.array' object has no attribute 'tobytes'
```

Python3 fails with:
```
Traceback (most recent call last):bmeta                     
  File "./gstatus.py", line 142, in main
    cluster.update_state(self_heal_backlog, client_status)
  File "/root/gstatus/gstatus/libgluster/cluster.py", line 564, in update_state
    task.status_str = task.find('./statusStr').text
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'status_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gstatus.py", line 244, in <module>
    main()
  File "./gstatus.py", line 143, in main
    except [GlusterFailedVolume, GlusterNotPeerNode] as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

Gluster is operational:
```
[root@glustera gstatus]# gluster pool list
UUID                                    Hostname        State
9ff2f29c-78a0-4490-9c60-32a752ffd80a    glusterb        Connected 
45854556-04d2-4c62-937f-326ca2cb8677    glusterc        Connected 
25e3c9b9-17e0-43c2-bd31-276381a4450f    glusterd        Connected 
dd6d1704-7049-4748-9916-b66b748656bb    glustere        Connected 
1f699dfd-15f8-4f14-83c0-62b695fad7e0    localhost       Connected 
[root@glustera gstatus]# gluster volume list
ctdbmeta
custdata
```

**Comment by blurpy** [comment]
I downloaded the tarball onto a server with CentOS 7 and that also fails:

```
[root@demoglusterfs1test gstatus-0.67]# python --version
Python 2.7.5

[root@demoglusterfs1test gstatus-0.67]# ./gstatus.py -s 
Traceback (most recent call last):  
  File "./gstatus.py", line 245, in <module>
    main()
  File "./gstatus.py", line 133, in main
    cluster.initialise()
  File "/root/gstatus/gstatus-0.67/gstatus/libgluster/cluster.py", line 97, in initialise
    self.define_nodes()
  File "/root/gstatus/gstatus-0.67/gstatus/libgluster/cluster.py", line 170, in define_nodes
    local_ip_list = get_ipv4_addr()  # Grab all IP's
  File "/root/gstatus/gstatus-0.67/gstatus/libutils/network.py", line 130, in get_ipv4_addr
    namestr = names.tobytes()
AttributeError: 'array.array' object has no attribute 'tobytes'
```

**Comment by blurpy** [comment]
I changed this:

```
  File "/root/gstatus/gstatus-0.67/gstatus/libutils/network.py", line 130, in get_ipv4_addr
    namestr = names.tobytes()
```

To this:

```
    namestr = names.tostring()
```

And it seems to have fixed the issue:

```
[root@demoglusterfs1test gstatus-0.67]# ./gstatus.py -s
 
     Product: Community          Capacity:  98.00 GiB(raw bricks)56                     
      Status: HEALTHY                        3.00 GiB(raw used)
   Glusterfs: 5.5                           49.00 GiB(usable from volumes)
  OverCommit: No                Snapshots:   0

   Nodes       :  3/  3		  Volumes:   6 Up
   Self Heal   :  3/  2		             0 Up(Degraded)
   Bricks      : 12/ 12		             0 Up(Partial)
   Connections :  7/  44                     0 Down

Status Messages
  - Cluster is HEALTHY, all_bricks checks successful
()
```

Not sure I understand the self-heal output. 3 out of 2 nodes are ok?

**Comment by sac** [comment]
Hi @hunter86bg,

Just today we merged patch which reworks gstatus entirely. The requirements and procedure to build is documented in README (https://github.com/gluster/gstatus/blob/master/README).

Installing glustercli-python
  - git clone https://github.com/gluster/glustercli-python.git
  - cd glustercli-python
  - python3 setup.py install

git clone https://github.com/gluster/gstatus.git

cd gstatus
chmod +x gstatus.py 
./gstatus.py --help
./gstatus.py -a

If you are looking for the self-heal and rebalance statuses it is not implemented yet. So far we have quota, snapshots, volume health ... 

I'll fix the setup.py for gstatus today so that gstatus can be installed to standard directories. For now you can use it from the repository directory.

We have self-heal, rebalance, geo-replication planned. If you are looking for any features let us know.

**Comment by hunter86bg** [comment]
@sac ,
definately something is wrong:
Git clone is OK:
```
[root@glustere ~]# git clone https://github.com/gluster/glustercli-python.git
Клониране и създаване на хранилище в „glustercli-python“…
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 464 (delta 7), reused 11 (delta 5), pack-reused 443
Получаване на обекти: 100% (464/464), 117.01 KiB | 688.00 KiB/s, действието завърши.
Откриване на съответните разлики: 100% (265/265), действието завърши.
[root@glustere ~]# cd glustercli-python/
```

Trying to install glustercli-python requires a dir that is missing (actually the last 2 are missing):
```
[root@glustere glustercli-python]# python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/local/lib/python3.6/site-packages/test-easy-install-18242.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.6/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
```

So I create the "python3.6/site-packages" in order to install:
```
[root@glustere glustercli-python]# mkdir -p  /usr/local/lib/python3.6/site-packages/
```
Then glustercli-python installes without errors.

Cloning gstatus:
```
[root@glustere ~]# git clone https://github.com/gluster/gstatus.git
Клониране и създаване на хранилище в „gstatus“…
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (39/39), done.
remote: Total 1004 (delta 16), reused 34 (delta 11), pack-reused 953
Получаване на обекти: 100% (1004/1004), 996.39 KiB | 1.56 MiB/s, действието завърши.
Откриване на съответните разлики: 100% (533/533), действието завърши.
[root@glustere ~]# cd gstatus/
```
Now we should chown gstatus.py , but there is no such thing:
```
[root@glustere gstatus]# ls -l gstatus.py
ls: няма достъп до 'gstatus.py': No such file or directory
[root@glustere gstatus]# ls -l
общо 64
drwxr-xr-x. 3 root root    62 12 авг 21,33 gstatus
-rw-r--r--. 1 root root  5739 12 авг 21,33 gstatus.spec
-rw-r--r--. 1 root root 35141 12 авг 21,33 LICENSE
-rw-r--r--. 1 root root   948 12 авг 21,33 Makefile
-rw-r--r--. 1 root root  5396 12 авг 21,33 README
-rw-r--r--. 1 root root    18 12 авг 21,33 requirements.txt
-rw-r--r--. 1 root root  1167 12 авг 21,33 setup.py
```

Trying to run the setup.py is not possible:
```
[root@glustere gstatus]# python3.6 setup.py install
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from gstatus import version
ImportError: cannot import name 'version'
[root@glustere gstatus]# python3.6 setup.py 
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from gstatus import version
ImportError: cannot import name 'version'
```
Actually the whole git repo represents:
```
[root@glustere gstatus]# tree
.
├── gstatus
│   ├── glusterlib
│   │   ├── cluster.py
│   │   ├── display_status.py
│   │   └── __init__.py
│   ├── __init__.py
│   ├── __main__.py
│   └── __pycache__
│       └── __init__.cpython-36.pyc
├── gstatus.spec
├── LICENSE
├── Makefile
├── README
├── requirements.txt
└── setup.py

3 directories, 12 files
```

**Comment by hunter86bg** [comment]
Any idea if a dependency is missing ?

**Comment by sac** [comment]
@hunter86bg we no longer have gstatus.py it was moved to gstatus/\_\_main\_\_.py this change was made to support the single binary builds.

Now coming to the issue you reported. Here are the steps you should follow:

```
  - git clone https://github.com/gluster/gstatus.git
  - cd gstatus
  - VERSION=1.0.0 make gen-version
  - python3 setup.py install
```

The ```VERSION=1.0.0 make gen-version ``` step creates the gstatus/version.py file which provides the version.
You can even run ```make gen-version``` by omitting the VERSION variable, in such case it will build the master.

Please try the above steps and let us know if that solves the issue.

Alternatively, you can follow the below steps as well:
```
$ curl -LO https://github.com/gluster/gstatus/releases/download/v1.0.0/gstatus
$ chmod +x gstatus
# ./gstatus -a
# ./gstatus --help
```

I am updating the README file to remove the reference to gstatus.py. Thanks for reporting.
