### ISSUE TITLE
KeyError Exception on Missing Brick

### ISSUE THREAD

**Issue by mikesmitty** [gluster/gstatus#31]
I'm running the gstatus package for CentOS 8 from [COPR](https://copr.fedorainfracloud.org/coprs/sac/gstatus/) with glusterfs 7.6, and with bricks missing it hits an exception:
```
# gstatus -a
 
Traceback (most recent call last):             
  File "/usr/bin/gstatus", line 245, in <module>
    main()
  File "/usr/bin/gstatus", line 143, in main
    cluster.update_state(self_heal_backlog, client_status)
  File "/usr/lib/python2.7/site-packages/gstatus/libgluster/cluster.py", line 531, in update_state
    self.volume[volume_name].update(xml_obj)
  File "/usr/lib/python2.7/site-packages/gstatus/libgluster/volume.py", line 128, in update
    self.brick_update(node)
  File "/usr/lib/python2.7/site-packages/gstatus/libgluster/volume.py", line 99, in brick_update
    node_info['fsName'],
KeyError: 'fsName'
```
The drive was in an i/o error status when this exception was occurring, if that's relevant:
```
# ll /data/glusterfs/volname1/
ls: cannot access '/data/glusterfs/volname1/brick2': Input/output error
total 0
drwxr-xr-x. 5 root root 70 Feb 17 11:59 brick1
d?????????? ? ?    ?     ?            ? brick2
```

**Comment by sac** [comment]
Please try https://github.com/gluster/gstatus/releases/download/v1.0.0/gstatus and let us know if it works for you.
