### ISSUE TITLE
gstatus source install missing version

### ISSUE THREAD

**Issue by ChristineTChen** [gluster/gstatus#53]
Hi, 

I'm trying to install gstatus from source via `pip install .`

I get the following error:

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-iu5z4zm1/setup.py", line 7, in <module>
        from gstatus import version
    ImportError: cannot import name 'version' from 'gstatus' (/tmp/pip-req-build-iu5z4zm1/gstatus/__init__.py)
```

Can this version file be included in the package?

**Comment by ChristineTChen** [comment]
cc @sac @aravindavk 

pinging for visibility, thanks

**Comment by aravindavk** [comment]
Install using,

```
curl -LO https://github.com/gluster/gstatus/releases/download/v1.0.4/gstatus
chmod +x ./gstatus
sudo mv ./gstatus /usr/local/bin/gstatus
gstatus --version
```

Source install is also documented here https://github.com/gluster/gstatus

**Comment by sac** [comment]
To install from source:

Installing from source

* Installing glustercli-python

```
git clone https://github.com/gluster/glustercli-python.git
cd glustercli-python
python3 setup.py install
```

Installing the gstatus tool:
* Using python-setuptools

```
git clone https://github.com/gluster/gstatus.git
cd gstatus
VERSION=1.0.4 make gen-version
python3 setup.py install
```

Version is updated once you run make gen-version.
