### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by thetuxinator** [gluster/gstatus#62]
Hi, no matter what i do, either using source or binary version, always getting this error:

 sudo gstatus -v
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/glustercli/cli/parsers.py", line 218, in parse_volume_info
    volumes.append(_parse_a_vol(volume_el))
  File "/usr/local/lib/python3.8/dist-packages/glustercli/cli/parsers.py", line 137, in _parse_a_vol
    'stripe': int(volume_el.find('stripeCount').text),
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/gstatus", line 11, in <module>
    load_entry_point('gstatus==1.0.6', 'console_scripts', 'gstatus')()
  File "/usr/local/lib/python3.8/dist-packages/gstatus-1.0.6-py3.8.egg/gstatus/__main__.py", line 73, in main
  File "/usr/local/lib/python3.8/dist-packages/gstatus-1.0.6-py3.8.egg/gstatus/glusterlib/cluster.py", line 37, in gather_data
  File "/usr/local/lib/python3.8/dist-packages/glustercli/cli/volume.py", line 188, in status_detail
    info(volname),
  File "/usr/local/lib/python3.8/dist-packages/glustercli/cli/volume.py", line 152, in info
    return parse_volume_info(volume_execute_xml(cmd),
  File "/usr/local/lib/python3.8/dist-packages/glustercli/cli/parsers.py", line 220, in parse_volume_info
    raise GlusterCmdOutputParseError(err)
glustercli.cli.parsers.GlusterCmdOutputParseError: 'NoneType' object has no attribute 'text'

**Comment by thetuxinator** [comment]
Ok, i understant thats a glustercli error and not a gstatus error

**Comment by madmax01** [comment]
i have same issue here as well.

with below Gluster 10.x  i had this Error once a Brick was down,....... but with Version 10.x  i have this Error the whole Time. Even with everything is healthy...   maybe the gstatus need an update to support newer Versions as well...

Hoping will be a fix?

**Comment by thetuxinator** [comment]
If i remember i fixed it by disabling stripe, see https://github.com/thetuxinator/glustercli-python however not sure as that was some time ago

**Comment by aravindavk** [comment]
> If i remember i fixed it by disabling stripe, see https://github.com/thetuxinator/glustercli-python however not sure as that was some time ago

New release was not available after your fix to the repo https://github.com/gluster/glustercli-python/pull/51

**Comment by thetuxinator** [comment]
> > If i remember i fixed it by disabling stripe, see https://github.com/thetuxinator/glustercli-python however not sure as that was some time ago
> 
> New release was not available after your fix to the repo [gluster/glustercli-python#51](https://github.com/gluster/glustercli-python/pull/51)

Missed that :D ok thx

**Comment by madmax01** [comment]
i installed curl -LO https://github.com/gluster/gstatus/releases/download/v1.0.7/gstatus

and with gluster 10.1  i see it working again. no Errors so far....

very nice guys ;)....... thx
