### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by madmax01** [gluster/gstatus#65]
Hi everyone,

Just as info.. also with latest gstatus and gluster 10.1  once inside an replication 1 brick is down > then other Gluster nodes getting an error. even if all is fine (apart of the 1 Brick down). As long the Volume is up > means is not emergency.

may an easy fix?

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/gstatus/__main__.py", line 77, in <module>
  File "/usr/bin/gstatus/__main__.py", line 73, in main
  File "/usr/bin/gstatus/glusterlib/cluster.py", line 37, in gather_data
  File "/usr/bin/gstatus/glustercli/cli/volume.py", line 189, in status_detail
  File "/usr/bin/gstatus/glustercli/cli/parsers.py", line 307, in parse_volume_status
AttributeError: 'NoneType' object has no attribute 'get'

thx

**Comment by sac** [comment]
Hi this is what I tried:

```
root@vm1:~# gstatus -a -v rep 

Cluster:
         Status: Healthy                 GlusterFS: 11dev
         Nodes: 2/2                      Volumes: 1/1

Volumes: 

rep
                Replicate          Started (PARTIAL) - 1/2 Bricks Up 
                                   Capacity: (56.17% used) 11.00 GiB/19.00 GiB (used/total)
                                   Bricks:
                                      Distribute Group 1:
                                         vm1:/data/r1   (Online)
                                         vm2:/data/r2   (Offline)
                                   Note: glusterd/glusterfsd is down in one or more nodes.
                                         Sizes might not be accurate.


```

And works fine for me. Can you please provide the volume details and the exact command you executed?

**Comment by madmax01** [comment]
i just used "gstatus"     command.... nothing extra as quick test..... and got error above.  this is when 1 gluster node was down.... then i had the issue across all other Nodes with the Error.

i had this with earlier Gluster Versions also.... currently i cannot test this with same Setup.

i look somewhere else in Lab and re/create... will paste then once i upgraded stack

**Comment by guinoise** [comment]
Same here, when one node is offline got an error. Either without any options (full status) or for a specific volume (like sac did).
`
gstatus
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/gstatus/__main__.py", line 77, in <module>
  File "/usr/bin/gstatus/__main__.py", line 73, in main
  File "/usr/bin/gstatus/glusterlib/cluster.py", line 37, in gather_data
  File "/usr/bin/gstatus/glustercli/cli/volume.py", line 189, in status_detail
  File "/usr/bin/gstatus/glustercli/cli/parsers.py", line 307, in parse_volume_status
AttributeError: 'NoneType' object has no attribute 'get'

gstatus -a -v HA
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/gstatus/__main__.py", line 77, in <module>
  File "/usr/bin/gstatus/__main__.py", line 73, in main
  File "/usr/bin/gstatus/glusterlib/cluster.py", line 35, in gather_data
  File "/usr/bin/gstatus/glusterlib/cluster.py", line 125, in _get_volume_details
  File "/usr/bin/gstatus/glustercli/cli/volume.py", line 179, in status_detail
  File "/usr/bin/gstatus/glustercli/cli/parsers.py", line 307, in parse_volume_status
AttributeError: 'NoneType' object has no attribute 'get'

`

**Comment by thetuxinator** [comment]
Same issue here, quite easy to reproduce, take 1 node offline (systemctl glusterd stop) and execute gstatus -o json . Looks like it tries to get the status of all bricks, but if 1 node is offline gluster volume status volname detail will not output detail status of that particular node's brick and thus its output is empty.

**Comment by madmax01** [comment]
May possible to get a new binary compiled ? ;)

i can also confirm today in an 4-way replication i tested to shutdown network ports,.... and each Gluster node blamed exact same like above.

but in Fact each Gluster own Brick is online > just cannot talk to each other.

**Comment by thetuxinator** [comment]
you don't need to recompile actually, the fix is not in gstatus but in glustercli-python and they merged it just some days ago, see https://github.com/gluster/glustercli-python/commit/1b03496dbecafe0e95ab6fce5b1d22261acb7b5e

**Comment by madmax01** [comment]
new version 1.0.8  works for me ;)

**Comment by proligde** [comment]
At first I thought 1.0.8 fixed it for me, too, but then I noticed that now some of my volumes are marked as DOWN in cases where the previous version threw the Traceback. Calling it again, all the Volumes are shown as UP again. It happens on every 4th call or sth. Just like the error. I notice there is a slightly longer delay when calling it, when that happens.

The gluster-volumes are in production use, work fine and don't have any issues. At least none that I can see.
